baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'Karim Matar Webstore'
primary: true
siteGroup: 5793ed2d-1dd5-4bd6-b70c-1c56d2460493 # Karim Matar Webstore
sortOrder: 1
