fieldLayouts:
  c36975de-b991-4d27-862a-c48e7a1e56b7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: a2068f29-0505-4b45-99a7-1038d5649228
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: fb112e52-e76b-4b49-8b00-b978b0116df8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b225808e-ba87-45b1-b29e-e5fff13cd7e7 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 005fc869-dc43-4746-9457-a303b6899681
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 32eef56c-5b41-439b-9a0a-c605a43cd157
        userCondition: null
fs: assets
handle: images
name: images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
