columnSuffix: null
contentColumnType: string
fieldGroup: d065c9b6-646f-4d79-a80f-69ee321e38e6 # Common
handle: navigation
instructions: null
name: navigation
searchable: false
settings:
  contentTable: '{{%matrixcontent_navigation}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
