fieldLayouts:
  df374500-1c47-43b8-86df-da651bc26536:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9d38ae0c-fc56-4900-bfe1-bb7c04fe33d3 # navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ec15b1a-4c2e-4baa-816f-08f12081d116
            userCondition: null
            warning: null
            width: 100
        name: navigation
        uid: 34836475-0cde-42fc-8360-f747d32d4a7f
        userCondition: null
handle: navigation
name: Navigation
sortOrder: 1
